---
- name: install required packages for ansible modules
  raw: dnf install --quiet --assumeyes python2 python2-dnf libselinux-python
  changed_when: false

- name: install vagrant and dependencies
  dnf: name={{ item }} state=present
  with_items:
  - vagrant
  - ruby-devel
  - libffi-devel
  - redhat-rpm-config

- name: install vagrant plugins
  dnf: name=vagrant-{{ item.key }} state=present
  with_dict: "{{ vagrant_plugins }}"
  when: item.value

- include: install_libvirt-Fedora.yml
  when: vagrant_plugins.libvirt

#  - name: 
#    unless: vagrant box list

#- name: open up firewalld for nfs service
#  firewalld: service={{ item }} permanent=true state=enabled immediate=true
#  with_items:
#    - nfs
#    - rpc-bind
#    - mountd

#- name: open up firewalld ports for nfs
#  firewalld: port={{ item }} permanent=true state=enabled immediate=true
#  with_items:
#    - 2049/udp
